config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  get '/features/configurable' => 'visitors#configurable'
  get '/features/custody' => 'visitors#custody'
  get '/features/peertopeer' => 'visitors#peertopeer'
  get '/features/opensource' => 'visitors#opensource'
  get '/stats' => 'visitors#stats'

  get '/dashboard' => 'page#dashboard'

  get '/dashboard/buy/create' => 'page#buy_create'
  get '/dashboard/buy/finalize/:buy_id' => 'page#buy_finalize_select'
  get '/dashboard/buy/kyc/:buy_id/:sell_id' => 'page#buy_kyc'
  get '/dashboard/buy/finalize/:buy_id/:sell_id' => 'page#buy_finalize_complete'

  get '/dashboard/sell/create' => 'page#sell_create'
  get '/dashboard/sell/kyc/:sell_id/:buy_id' => 'page#sell_kyc'

  get '/dashboard/settings' => 'page#settings'

  post '/dashboard/settings/add_wallet' => 'settings#add_wallet'
  post '/dashboard/settings/add_stripe_info' => 'settings#add_stripe_info'

  get '/users/two_factor' => 'users#two_factor'
  post '/users/two_factor_check' => 'users#two_factor_check'
  post '/users/two_factor_generate' => 'users#two_factor_generate'
  devise_for :users, :controllers => {:sessions => "sessions"}
  resources :users
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user
	has_many :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
	has_one :address
	has_one :order
	has_many :order_additionals
end

app/models/order_additional.rb
class OrderAdditional < ApplicationRecord
	belongs_to :order
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/stripe_info.rb
class StripeInfo < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :addresses
  has_many :orders, :through => :addresses
  has_one :stripe_info
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :verify_two_fact, :except => [:generate_two_fact]
  include SettingsHelper
  
  def verify_two_fact
  	if current_user && current_user.two_fac_code != nil
  		redirect_to '/users/two_factor'
  	end
  end

  def generate_two_fact
    if getTokenBoolean('TWILIO_2FA') && current_user.phone && current_user.phone != ""
      @two_factor = 100000 + rand(900000)
      current_user.two_fac_code = @two_factor
      current_user.save

      #Need to actually send code here
    end
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
	before_action :authenticate_user!
	def dashboard
	end
	
	def settings
		@stripe_public_exists = (current_user.stripe_info.present? && current_user.stripe_info.publishable_key.present?)
		@stripe_private_exists = (current_user.stripe_info.present? && current_user.stripe_info.secret_key.present?)
		
		@buy_status = current_user.addresses.count > 0
		@sell_status = @buy_status && @stripe_public_exists && @stripe_private_exists
	end

	def buy_create
	end

	def buy_kyc
	end

	def buy_finalize_select
	end

	def buy_finalize_complete
	end

	def sell_create
	end

	def sell_kyc
	end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  after_filter :after_login, :only => :create

  def after_login
  	generate_two_fact
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
	protect_from_forgery with: :null_session

	def add_wallet
		@user = current_user

		@valid_address = false
		@wrong_network = getTokenBoolean('BITCOIN_NETWORK') 
		if @wrong_network
			Bitcoin.network = :bitcoin
		else
			Bitcoin.network = :testnet3
		end

		@valid_address = Bitcoin::valid_address?(params['public_address']) && current_user.addresses.where({:public_key => params['public_address']}).count == 0

		if @valid_address
			@address = Address.new
			@address.public_key = params['public_address']
			@address.user_id = @user.id
			@address.save
			
			@code = 200
			@results = {
				:status => @code,
				:message => "Address Stored Successfully"
			}

			render json: @results, code: @code
		else
			@code = 400
			@results = {
				:status => @code,
				:error => "Incorrect Bitcoin Network / Invalid Address / Duplicate Address"
			}
			render json: @results, code: @code
		end
	end

	def add_stripe_info
		@user = current_user

		@wrong_network = getTokenBoolean('STRIPE_NETWORK') 
		if @wrong_network
			@wrong_network = (params['stripe_public'].include?('pk_test') || params['stripe_public'].include?('sk') || params['stripe_private'].include?('sk_test') || params['stripe_private'].include?('pk'))
		else
			@wrong_network = (params['stripe_public'].include?('pk_live') || params['stripe_public'].include?('sk') || params['stripe_private'].include?('sk_live') || params['stripe_private'].include?('pk'))
		end

		if !@wrong_network && !@user.stripe_info
			@stripe_info = StripeInfo.new
			@stripe_info.publishable_key = params['stripe_public'].strip
			@stripe_info.secret_key = params['stripe_private'].strip
			@stripe_info.user_id = @user.id
			@stripe_info.save

			@code = 200
			@results = {
				:status => @code,
				:message => "Stripe Info Stored Successfully"
			}

			render json: @results, code: @code
		else
			@code = 400
			@results = {
				:status => @code,
				:error => "Incorrect Stripe Network / Incorrect Key Order / Duplicate Keys"
			}
			render json: @results, code: @code
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  skip_before_filter :verify_two_fact, except: [:index, :show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

  def two_factor
    @phone = current_user.phone
    @updated_at = current_user.updated_at
  end 

  def two_factor_check
    @code_set = current_user.two_fac_code
    @code_provided = params[:code]

    if @code_set == @code_provided
      current_user.two_fac_code = nil
      current_user.save
      redirect_to '/dashboard/'
    else
      redirect_to :back, :alert => "Wrong Code."
    end
  end

  def two_factor_generate
    if current_user.updated_at < 10.minutes.ago
      generate_two_fact
      redirect_to :back, :message => "New Code Sent."
    else
      redirect_to :back, :alert => "New Codes Can Only Be Generated Every Ten Minutes."
    end
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	def configurable
		@allow_seller_delays = getTokenBoolean('ALLOW_SELLER_DELAYS')
		@allow_seller_kyc_collect = getTokenBoolean('ALLOW_SELLER_KYC_COLLECT')
		@allow_seller_limits = getTokenBoolean('ALLOW_SELLER_KYC_COLLECT')
		@seller_fee = getTokenNumber("SELLER_FEE") rescue 0
		@buyer_fee = getTokenNumber("BUYER_FEE") rescue 0
		@config_provider = getToken('CONFIG_PROVIDER')
		@mailgun_email = getTokenBoolean('MAILGUN_EMAIL')
		@twilio_twofa = getTokenBoolean('TWILIO_2FA')
		@withdrawl = getTokenBoolean('WITHDRAWL_METHOD')
		@bitcoin_network = getToken('BITCOIN_NETWORK') == 'livenet' rescue false
		@stripe_network = getToken('STRIPE_NETWORK') == 'production' rescue false
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include SettingsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
	@CONFIG_PROVIDER = nil

	def getConfig
		@env = ENV['CONFIG_PROVIDER']
		@db = Setting.where({:key => 'CONFIG_PROVIDER'}).first

		if @env
			return @env
		elsif @db
			return @db
		end

		return ""
	end
	
	def getTokenNumber(key)
		getToken(key).to_f
	end

	def getTokenBoolean(key)
		getToken(key) == "true"
	end
	
	def getToken(key)
		@CONFIG_PROVIDER = getConfig if !@CONFIG_PROVIDER
		
		if @CONFIG_PROVIDER && @CONFIG_PROVIDER == 'env'
			@env = ENV[key]

			if @env
				return @env
			end
			
			return ""
		elsif @CONFIG_PROVIDER && @CONFIG_PROVIDER == 'db'
			@db = Setting.where({:key => key}).first

			if @db
				return @db.value
			end

			return ""
		else
			return ""
		end
	end
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class="container">
  <hr>
  <footer>
      <div class="row">
          <div class="col-lg-12">
              <p>Copyright &copy; SecBitEx 0 - <%= Date.current.year + 1 %></p>
          </div>
      </div>
  </footer>
</div>
<!-- /.container -->

app/views/layouts/_gentelella_footer.html.erb
<!-- footer content -->
<footer style="margin-top: 0px !important" >
  <div class="top_nav" style="float: right; margin-left: 230px !important">
    <p>Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a></p>
    <p>Copyright &copy; SecBitEx 0 - <%= Date.current.year + 1 %></p>
  </div>
  <div class="clearfix"></div>
</footer>
<!-- /footer content -->

app/views/layouts/_gentelella_sidenav.html.erb
<div class="main_container">

  <div class="col-md-3 left_col">
    <div class="left_col scroll-view" style="background-color: #2A3F54">

      <div class="navbar nav_title" style="border: 0;">
        <a href="index.html" class="site_title">
          <i class="fa fa-lock"></i> <span>SecBitEx</span></a>
      </div>
      <div class="clearfix"></div>


      <!-- menu profile quick info -->
      <div class="profile">
        <div class="profile_pic">
          <%= image_tag "http://placehold.it/48x48", :class => "img-circle profile_img"  %>
        </div>
        <div class="profile_info">
          <span>Welcome,</span>
          <h2><%= current_user.name %></h2>
        </div>
      </div>
      <!-- /menu profile quick info -->

      <br />

      <!-- sidebar menu -->
      <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

        <div class="menu_section" style="margin-top: 100px">
          <h3>Menu</h3>
          <ul class="nav side-menu">
            <li class=<%= "#{current_page?(dashboard_path) ? 'active' : 'nil'} " %>><a href='/dashboard'><i class="fa fa-dashboard"></i> Dashboard </a>
            </li>
            <li class=<%= "#{current_page?(dashboard_buy_create_path) ? 'active' : 'nil'} " %>><a href='/dashboard/buy'><i class="fa fa-btc"></i> Buy Bitcoins</a>
            </li>
            <li class=<%= "#{current_page?(dashboard_sell_create_path) ? 'active' : 'nil'} " %>><a href='/dashboard/sell'><i class="fa fa-btc"></i> Sell Bitcoins</a>
            </li>
            <li class=<%= "#{current_page?(dashboard_settings_path) ? 'active' : 'nil'} " %>><a href='/dashboard/settings'><i class="fa fa-cog"></i> Exchange Settings</a>
            </li>
          </ul>
        </div>
      </div>
      <!-- /sidebar menu -->

      <!-- /menu footer buttons -->
      <div class="sidebar-footer hidden-small" style="padding-top: 100%; z-index: -1">
        <h5 class="text-center">Account</h5>
        <%= link_to 'Settings', edit_user_registration_path, :style => 'width: 50%' %>
        <%= link_to 'Logout', destroy_user_session_path, :method=>'delete', :style => 'width: 50%'  %>
      </div>
      <!-- /menu footer buttons -->
    </div>
  </div>

app/views/layouts/_gentelella_topnav.html.erb
<!-- top navigation -->
<div class="top_nav">

  <div class="nav_menu">
    <nav class="" role="navigation">
      <ul class="nav navbar-nav navbar-right">
        <li role="presentation" class="dropdown">
          <a href="/dashboard/" class="dropdown-toggle info-number" data-toggle="dropdown">
            <i class="fa fa-envelope-o"></i>
            <span class="badge bg-green">6</span>
          </a>
        </li>
      </ul>
    </nav>
  </div>

</div>
<!-- /top navigation -->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit Account', edit_user_registration_path, :class => 'navbar-brand'  %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete', :class => 'navbar-brand'  %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path, :class => 'navbar-brand'  %></li>
  <li><%= link_to 'Join Us', new_user_registration_path, :class => 'navbar-brand'  %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home Page', root_path, class: 'navbar-brand' %>
      <%= link_to 'Statistics', stats_path, class: 'navbar-brand' %>
      <% if user_signed_in? %>
        <%= link_to 'Dashboard', dashboard_path, :class => 'navbar-brand' %></li>
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SecBitEx" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "SecBitEx" %>">
    <%= stylesheet_link_tag 'application_main', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/page.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "SecBitEx" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "SecBitEx" %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Custom Fonts -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body class="nav-md" style="padding: 0px !important; margin: 0px !important; background-color: white">
  <div class="container body">
    <%= render "layouts/gentelella_sidenav" %>
    <%= render "layouts/gentelella_topnav" %>
    <%= render 'layouts/messages' %>

    <%= yield %>

    <%= render "layouts/gentelella_footer" %>
  </body>
</html>

app/views/page/buy_create.html.erb
<div class="right_col" role="main" style="background-color: #FFFFFF">
	<div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Buy Bitcoins</h3>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <h4 class="x_title">Purchase Bitcoins</h4>
          <div class="row">
          	
          </div>
				</div>
			</div>
		</div>
</div>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/two_factor.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-6'>
      <h1 class="page-header">
        Are you <b>you?</b>
      </h1>

      <h3>We need to be sure you're you.</h3>
      <h3>We sent a code to your phone: <b><%= @phone %></b></h3>
    </div>
    <div class="col-md-6">
      <div class="authform">
      	<%= form_tag(users_two_factor_check_path, method: "post") do |f| %>
          <h3>Two Factor Code</h3>
          <%= label_tag :code %>
          <%= text_field_tag :code, nil, :autofocus => true, class: 'form-control' %>
          <h5 style="margin-top: 20px; float:right">Your code was sent <%= distance_of_time_in_words_to_now(@updated_at) %> ago</h5>
          <%= submit_tag "Here's My Code", :class => 'btn-primary form-control' %>
      	<% end %>

        <%= form_tag(users_two_factor_generate_path, method: "post") do |f| %>
          <h3>Generate New Code</h3>
          <h5 style="margin-top: 10px; float:right">More than 10 minutes required. Sent <%= distance_of_time_in_words_to_now(@updated_at) %> ago</h5>
          <%= submit_tag "Give Me A New Code", :class => 'btn-primary form-control' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/visitors/configurable.html.erb
<div class="container">

    <!-- Marketing Icons Section -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Highly Configurable
        </h1>
      </div>
      <h4 class='text-center'>Why settle for something that's 'Close Enough'?
      <br> Your idea of an exchange should be "Exactly As I Want It"</h4>
    </div>

    <!-- Features Section -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Configuration Options</h2>
        </div>
        <div class="col-md-6">
            <p>Use database-level configuration or environment level configuration</p>
            <ul>
                <li><strong>Manual or Automatic Withdrawls For Greater Security</strong></li>
                <li><strong>Twilio 2FA - On or Off</strong></li>
                <li><strong>Mailgun Emails - On or Off</strong></li>
                <li>Allow Sellers to Collect KYC</li>
                <li>Allow Sellers to Delay Transactions</li>
                <li>Allow Sellers to Limit To People Who Have Transacted X Amount</li>
                <li>Customizable Seller Fees</li>
            </ul>
        
            <p>Current Setup - This Instance</p>
            <ul> 
              <li>Configuration Provider: <b><%= @config_provider rescue "None Provided" %></b></li>
              <li>Withdrawal Configuration: <b><%= @withdrawl ? "Automatic" : "Manual" %></b></li>
              <li>Buyer Fee: <b><%= @buyer_fee %>%</b></li>
              <li>Seller Fee: <b><%= @seller_fee %>%</b></li>
              <li>Bitcoin Network: <b><%= @bitcoin_network ? "Livenet" : "Testnet" %></b></li>
              <li>Stripe Network: <b><%= @stripe_network ? "Production" : "Test" %></b></li>
              <li>Twilio 2FA: <b><%= @twilio_twofa ? "Active" : "Inactive" %></b></li>
              <li>Mailgun Email: <b><%= @mailgun_email ? "Active" : "Inactive" %></b></li>
              <li>Sellers Can Collect KYC: <b><%= @allow_seller_kyc_collect ? "Yes" : "No" %></b></li>
              <li>Sellers Can Delay Orders: <b><%= @allow_seller_delays ? "Yes" : "No" %></b></li>
              <li>Sellers Can Set Min-Buy Limits: <b><%= @allow_seller_limits ? "Yes" : "No" %></b></li>
            </ul>

            <p> Your exchange should be an unique as your ideas on how to run an exchange.</p>
            <p><b>Because One Size Fits None. #StrongIndepentExchangeThatDon'tNeedNoInvestor</b></p>
        </div>
        <div class="col-md-6">
            <img class="img-responsive" src="http://placehold.it/700x450&text=Configuration 101" alt="">
        </div>
    </div>
    <!-- /.row -->
</div>

app/views/visitors/custody.html.erb
<div class="container">

    <!-- Marketing Icons Section -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Custody
        </h1>
      </div>
      <h4 class='text-center'>Because no amount of pride from holding customer funds is worth the following headline: <br> "Your Exchange Has Been Hacked, All Funds Stolen"</h4>
    </div>

    <!-- Features Section -->
    <div class="row">
        <div class="col-lg-12">
          <h2 class="page-header">Custody Features</h2>
        </div>
        <div class="col-md-6">
          <ul>
            <li>Accept deposits right at the moment a trade is executed</li>
            <li>Denominate your wallets from public keys</li>
            <li>Inflate your valuation by using the public key balance as "your wallet balance"</li>
            <li>Don't let a little thing like greed get in the way of your exchange succeeding</li>
          </ul>
          <p><b>Because Exchanges Should Only Hold Trade Funds. #ReasonableThings</b></p>
        </div>
        <div class="col-md-6">
            <img class="img-responsive" src="http://placehold.it/700x450&text=Public Keys 101" alt="">
        </div>
    </div>
    <!-- /.row -->
</div>

app/views/visitors/opensource.html.erb
<div class="container">

    <!-- Marketing Icons Section -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Open Source
        </h1>
      </div>
      <h4 class='text-center'>Because MIT Licenses Are A Thing Of Beauty.<br> And Not Using Them Is Terrible.</h4>
    </div>

    <!-- Features Section -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Open Source As A Feature</h2>
        </div>
        <div class="col-md-6">
        <ul>
          <li><strong><a href="https://github.com/AtheistOfFail/SecBitEx">All Code</a></strong></li>
          <li><strong><a href="https://github.com/AtheistOfFail/SecBitEx/README.md">All Configuration</a></strong></li>
          <li><strong><a href="https://github.com/AtheistOfFail/SecBitEx/README.md">Deployment Instructions</a></strong></li>
          <li><strong><a href="https://github.com/AtheistOfFail/SecBitEx/pulls">Open To Pull Requests</a></strong></li>
        </ul>
        <p><b>Because If You Can't Audit It, It Isn't Worth A Penny. #JustProgrammerThings</b></p>
        </div>
        <div class="col-md-6">
            <img class="img-responsive" src="http://placehold.it/700x450&text=Security By Openness 101" alt="">
        </div>
    </div>
    <!-- /.row -->
</div>

app/views/visitors/peertopeer.html.erb
<div class="container">

    <!-- Marketing Icons Section -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Peer To Peer
        </h1>
      </div>
      <h4 class='text-center'>Because No Exchange Should Hold USD Balances.<br> Because They're 'Bitcoin Exchanges'.</h4>
    </div>

    <!-- Features Section -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Peer To Peer As A Feature</h2>
        </div>
        <div class="col-md-6">
        <ul>
          <li>Sellers supply their own Stripe credentials (public/private keypair)</li>
          <li>Buyers purchase through Stripe Checkout JS (using seller credentials)</li>
          <li>You don't touch the money, no liability, no issues</li>
        </ul>
        <p><b>Because Paper Money Is Nasty. #JustStripeThings</b></p>
        </div>
        <div class="col-md-6">
            <img class="img-responsive" src="http://placehold.it/700x450&text=Abusing Stripe 101" alt="">
        </div>
    </div>
    <!-- /.row -->
</div>